"use client";

export default function AuditVs() {
  return (
    <section className="w-full bg-white text-black py-16 md:py-24 px-6 md:px-12 flex justify-center">
      <div className="max-w-[1360px] w-full grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-16 items-start">
        {/* LEFT COLUMN: Text Content Block */}
        <div className="lg:col-span-5 space-y-4 text-left lg:pt-4">
          {/* Changed from font-extrabold to font-bold */}
          <span className="block text-[14px] font-bold uppercase tracking-wider text-black">
            AUDIT VS AUDIT
          </span>

          {/* Toned down from font-[800] to font-[700] / bold */}
          <h2 className="text-[34px] md:text-[44px] font-bold text-[#8A2BE2] leading-[1.15] tracking-tight">
            Not all SEO audits are worth the paper they're printed on
          </h2>

          {/* Lightened body description to normal weight with clean leading */}
          <p className="text-[16px] md:text-[17px] font-normal text-black leading-[1.5] max-w-[450px]">
            Most “free audits” are a software export with a sales pitch stapled
            to the back. They tell you what triggered a warning — never why it
            matters for your business, or what to do about it first.
          </p>
        </div>

        {/* RIGHT COLUMN: Two Wide Comparison Cards */}
        <div className="lg:col-span-7 grid grid-cols-1 sm:grid-cols-2 gap-6 w-full lg:pt-2">
          {/* Card 1: Vanity Traffic */}
          <div className="bg-black text-white p-8 md:p-9 rounded-[16px] min-h-[240px] flex flex-col justify-start space-y-4 shadow-sm">
            {/* Reduced heading from font-[700] to font-[600] semi-bold */}
            <h3 className="text-[20px] font-semibold tracking-tight">
              The typical automated audit
            </h3>
            {/* Set text weight to absolute light/normal weight tracking */}
            <ul className="space-y-2.5 text-[14px] md:text-[14.5px] font-normal opacity-90">
              <li className="flex items-start">
                <span className="mr-2 select-none">•</span>
            Generated by a crawler in minutes, sold as expertise
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none">•</span>
                Hundreds of undifferentiated warnings, no priorities
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none">•</span>
                Ignores your market, buyers and competitors
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none">•</span>
            Designed to scare you into a retainer
              </li>
            </ul>
          </div>

          {/* Card 2: Qualified B2B Demand */}
          <div className="bg-[#8A2BE2] text-white p-8 md:p-9 rounded-[16px] min-h-[240px] flex flex-col justify-start space-y-4 shadow-sm">
            {/* Reduced heading from font-[700] to font-[600] semi-bold */}
            <h3 className="text-[20px] font-semibold tracking-tight">
              Our senior-led B2B SEO audit
            </h3>
            {/* Set text weight to absolute light/normal weight tracking */}
            <ul className="space-y-2.5 text-[14px] md:text-[14.5px] font-normal opacity-90">
              <li className="flex items-start">
                <span className="mr-2 select-none">•</span>
                Manually conducted by a senior B2B specialist
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none">•</span>
            Every finding ranked by effort vs commercial impact
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none">•</span>
                Benchmarked against the competitors actually beating you
              </li>
              <li className="flex items-start">
                <span className="mr-2 select-none">•</span>
                A standalone deliverable you own — act on it with anyone
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}
